languageCode = "zh-tw"
languageName = "正體中文"
weight = 1
title = ""

[params]
  displayName = "ZH-TW"
  isoCode = "zh-tw"
  rtl = false
  dateFormat = "2 January 2006"
  logo = ""
  # secondaryLogo = "PATH"
  description = ""
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Alan"
  image = ""
  headline = ""
  bio = ""
  links = [
  ]

  